version: '3.8'

services:
  tools:
    container_name: devops-tools
    image: satishweb/devops-tools
    # export FIXUID=$(id -u)
    # export FIXGID=$(id -g)
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    command: sleep infinity
    restart: unless-stopped
    tty: true
    working_dir: ${HOME}
    network_mode: "host"
    # dns:
    #   - 208.67.222.222
    #   - 208.67.220.220
    environment:
      - HOME=${HOME}
      - SHELL=/usr/bin/zsh
      - USER=ubuntu
      - OPENAI_API_KEY=SET-ME
      - OPENAI_MAX_TOKENS=1000
      - OPENAI_MODEL=gpt-3.5-turbo
      - OPENAI_PROXY=
      - OPENAI_TEMPERATURE=0.2
      - USER_DEFAULT_PROMPT_MODE=exec
      - USER_PREFERENCES="Never execute any commands without my confirmation!"
      # - DEBUG=1
    # ports:
    #   - "18000-19000:18000-19000"
    volumes:
      - ${HOME}/.kube:${HOME}/.kube
      - ${HOME}/.saml2aws:${HOME}/.saml2aws
      - ${HOME}/.aws:${HOME}/.aws
      # - ${HOME}/.gnupg:${HOME}/.gnupg
      - ${HOME}/.gitconfig:${HOME}/.gitconfig
      - ${HOME}/.git-credentials:${HOME}/.git-credentials
      - ${HOME}/.ssh:${HOME}/.ssh
      - ${HOME}/.vim:${HOME}/.vim
      - ${HOME}/.tmux.conf:${HOME}/.tmux.conf
      - ${HOME}/.docker:${HOME}/.docker
      # - ${HOME}/.colima:${HOME}/.colima
      - ${HOME}/Documents:${HOME}/Documents
      - ./entrypoint.sh:/entrypoint.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/sources:${HOME}/sources
