version: '3.8'

services:
  devops-tools:
    container_name: devops-tools
    image: satishweb/devops-tools:v1.27.1
    # export FIXUID=$(id -u)
    # export FIXGID=$(id -g)
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    command: sleep infinity
    restart: unless-stopped
    tty: true
    working_dir: ${HOME}
    network_mode: "host"
    environment:
      - HOME
      # - DEBUG=1
    # ports:
    #   - "18000-19000:18000-19000"
    volumes:
      - ${HOME}/.kube:${HOME}/.kube
      - ${HOME}/.saml2aws:${HOME}/.saml2aws
      - ${HOME}/.aws:${HOME}/.aws
      - ${HOME}/.gnupg:${HOME}/.gnupg
      - ${HOME}/.gitconfig:${HOME}/.gitconfig
      - ${HOME}/.ssh:${HOME}/.ssh
      - ${HOME}/.vim:${HOME}/.vim
      # - ${HOME}/.tmux.conf:${HOME}/.tmux.conf
      - ${HOME}/.devops-tools-home/.zsh_history:${HOME}/.zsh_history
      - ${HOME}/.zsh_history:${HOME}/.zsh_history
      - ${HOME}/.docker:${HOME}/.docker
      - ${HOME}/Documents:${HOME}/Documents
      # - ./entrypoint.sh:/entrypoint.sh
      - /var/run/docker.sock:/var/run/docker.sock
